let
  Source = #"srcADUser Resources",
  exp_Person = Table.ExpandRecordColumn(Source, "person", {"cn"}, {"userId"}),
  exp_User = Table.ExpandRecordColumn(exp_Person, "user", {"userPrincipalName"}, {"userPrincipalName"}),
  rem_Columns = Table.RemoveColumns(exp_User, {"organizationalPerson", "msExchCustomAttributes"}),
  exp_Top = Table.ExpandRecordColumn(rem_Columns, "top", {"memberOf"}, {"top.memberOf"}),
  exp_list = Table.ExpandListColumn(exp_Top, "top.memberOf"),
  exp_record = Table.ExpandRecordColumn(exp_list, "top.memberOf", {"cn"}, {"mog.groupId"}),
  #"Transform columns" = Table.TransformColumnTypes(exp_record, {{"mog.groupId", type text}}),
  #"Replace errors" = Table.ReplaceErrorValues(#"Transform columns", {{"mog.groupId", null}}),
  #"Lowercased text" = Table.TransformColumns(#"Replace errors", {{"userPrincipalName", each Text.Lower(_), type nullable text}})
in
  #"Lowercased text"
